// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: observables/MutableObservableProperty.shared.kt
// Package: com.lightningkite.khrysalis.observables
import Foundation

open class MutableObservableProperty<T> : ObservableProperty<T> {
    override public init() {
        super.init()
        //Necessary properties should be initialized now
    }
    
    override open var value: T { get { TODO() } set { TODO() } }
    open func update() -> Void { TODO() }
}


