// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: observables/ObservableProperty.shared.kt
// Package: com.lightningkite.khrysalis.observables
import RxSwift
import Foundation

open class ObservableProperty<T> {
    public init() {
        //Necessary properties should be initialized now
    }
    
    open var value: T { get { TODO() } }
    open var onChange: Observable<T> { get { TODO() } }
}



