// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: observables/TransformedMutableObservableProperty2.shared.kt
// Package: com.lightningkite.khrysalis.observables
import Foundation

public class TransformedMutableObservableProperty2<A, B> : MutableObservableProperty<Any> {
    public var basedOn: MutableObservableProperty<A>
    public var read: @escaping  (A) -> B
    public var write: @escaping  (A, B) -> A
    override public init(basedOn: MutableObservableProperty<A>, read: @escaping  (A) -> B, write: @escaping  (A, B) -> A) {
        self.basedOn = basedOn
        self.read = read
        self.write = write
        self.onChange = self.basedOn.onChange.map(p0: { (it: Any) -> Any in self.read(it) })
        super.init()
    }
    
    override public func update() -> Void {
        self.basedOn.update()
    }
    
    override public var value: B {
        get {
            return self.read(self.basedOn.value)
        }
        set(value) {
            self.basedOn.value = self.write(self.basedOn.value, value)
        }
    }
    override public let onChange: Observable<B>
}

public extension MutableObservableProperty {
    func mapWithExisting<B>(read: @escaping  (T) -> B, write: @escaping  (T, B) -> T) -> MutableObservableProperty<B> {
        return TransformedMutableObservableProperty2(basedOn: self, read: read, write: write)
    }
}

