// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: views/EntryPoint.shared.kt
// Package: com.lightningkite.khrysalis.views
import { ViewGenerator } from './ViewGenerator.shared'
import { ObservableStack } from '../observables/ObservableStack.shared'

//! Declares com.lightningkite.khrysalis.views.EntryPoint
export interface EntryPoint {
    
    handleDeepLink(schema: string, host: string, path: string, params: Map<string, string>): void 
    readonly mainStack: (ObservableStack<ViewGenerator> | null);
    
}
export namespace EntryPointDefaults {
    export function handleDeepLink(this_: EntryPoint, schema: string, host: string, path: string, params: Map<string, string>): void {
        console.log(`Empty handler; ${schema}://${host}/${path}/${params}`);
    }
    export function getMainStack(this_: EntryPoint): (ObservableStack<ViewGenerator> | null) { return null; }
}

