// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: views/ImageView.shared.kt
// Package: com.lightningkite.khrysalis.views
import { xImageViewLoadImage } from './ImageView.actual'
import { xVideoThumbnail } from '../Video.actual'
import { Video } from '../Video.shared'
import { Image } from '../Image.shared'
import { SubscriptionLike } from 'rxjs'
import { xDisposableForever } from '../rx/DisposeCondition.actual'

//! Declares com.lightningkite.khrysalis.views.loadVideoThumbnail>android.widget.ImageView
export function xImageViewLoadVideoThumbnail(this_: HTMLImageElement, video: (Video | null)): void {
    if (video === null) { return }
    xImageViewLoadImage(this_, null);
    xDisposableForever<SubscriptionLike>(xVideoThumbnail(video!, undefined, undefined).subscribe((it: Image): void => {
                xImageViewLoadImage(this_, it);
            }, (it: any): void => {
                xImageViewLoadImage(this_, null);
    }));
}
