// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: views/SelectDateMonthCVD.shared.kt
// Package: com.lightningkite.khrysalis.views
// FQImport: com.lightningkite.khrysalis.views.SelectDateMonthCVD.drawDay.canvas TS canvas
// FQImport: com.lightningkite.khrysalis.views.SelectDateMonthCVD.drawDay.inner TS inner
// FQImport: com.lightningkite.khrysalis.views.SelectDateMonthCVD.dayPaint TS dayPaint
// FQImport: com.lightningkite.khrysalis.views.SelectDateMonthCVD.measure.height TS height
// FQImport: com.lightningkite.khrysalis.views.SelectDateMonthCVD.invalidate TS invalidate
// FQImport: com.lightningkite.khrysalis.views.SelectDateMonthCVD.drawDay.day TS day
// FQImport: com.lightningkite.khrysalis.views.MonthCVD TS MonthCVD
// FQImport: android.graphics.RectF TS RectF
// FQImport: com.lightningkite.khrysalis.time.DateAlone TS DateAlone
// FQImport: android.util.DisplayMetrics TS DisplayMetrics
// FQImport: com.lightningkite.khrysalis.views.SelectDateMonthCVD.measure.width TS width
// FQImport: com.lightningkite.khrysalis.views.SelectDateMonthCVD.onTap.day TS day
// FQImport: com.lightningkite.khrysalis.rx.forever>io.reactivex.disposables.Disposable TS ioReactivexDisposablesDisposableForever
// FQImport: com.lightningkite.khrysalis.views.CalendarDrawing.dayBackground TS dayBackground
// FQImport: com.lightningkite.khrysalis.views.SelectDateMonthCVD.selectedDayPaint TS selectedDayPaint
// FQImport: com.lightningkite.khrysalis.views.MonthCVD.measure TS measure
// FQImport: com.lightningkite.khrysalis.views.CalendarDrawing TS CalendarDrawing
// FQImport: com.lightningkite.khrysalis.observables.StandardObservableProperty TS StandardObservableProperty
// FQImport: com.lightningkite.khrysalis.views.SelectDateMonthCVD.selected TS selected
// FQImport: com.lightningkite.khrysalis.views.SelectDateMonthCVD.drawDay.showingMonth TS showingMonth
// FQImport: android.graphics.Paint TS Paint
// FQImport: com.lightningkite.khrysalis.views.SelectDateMonthCVD.measure.displayMetrics TS displayMetrics
// FQImport: com.lightningkite.khrysalis.views.CalendarDrawing.day TS day
// FQImport: com.lightningkite.khrysalis.observables.MutableObservableProperty TS MutableObservableProperty
// FQImport: com.lightningkite.khrysalis.views.SelectDateMonthCVD.selectedPaint TS selectedPaint
import { DateAlone } from '../time/DateAlone.actual'
import { DisplayMetrics } from './DisplayMetrics.actual'
import { safeEq } from '../Kotlin'
import { CalendarDrawing, MonthCVD } from './MonthCVD.shared'
import { copyDateAloneMod } from '../time/Date.actual'
import { Paint } from './draw/Paint.actual'
import { StandardObservableProperty } from '../observables/StandardObservableProperty.shared'
import { RectF } from './geometry/RectF.actual'
import { MutableObservableProperty } from '../observables/MutableObservableProperty.shared'
import { ioReactivexDisposablesDisposableForever } from '../rx/DisposeCondition.actual'

//! Declares com.lightningkite.khrysalis.views.SelectDateMonthCVD
export class SelectDateMonthCVD extends MonthCVD {
    public constructor() {
        super();
        this.selected = new StandardObservableProperty(null, undefined);
        let temp_357;
        if ((temp_357 = this.selected.value) !== null) { 
            this.currentMonthObs.value = copyDateAloneMod(temp_357, Date.prototype.setDate, 1);
        };
        ioReactivexDisposablesDisposableForever(this.selected.onChange.subscribe( (value) => {
                    this?.invalidate()
        }, undefined, undefined));
        this.selectedDayPaint = new Paint();
        this.selectedPaint = new Paint();
    }
    
    public generateAccessibilityView(): (HTMLElement | null) { return null; }
    
    public selected: MutableObservableProperty<(DateAlone | null)>;
    
    
    
    
    public readonly selectedDayPaint: Paint;
    
    public readonly selectedPaint: Paint;
    
    
    public drawDay(canvas: CanvasRenderingContext2D, showingMonth: DateAlone, day: DateAlone, displayMetrics: DisplayMetrics, outer: RectF, inner: RectF): void {
        if (safeEq(day, this.selected.value)){
            CalendarDrawing.INSTANCE.dayBackground(canvas, inner, this.selectedPaint);
            CalendarDrawing.INSTANCE.day(canvas, showingMonth, day, inner, this.selectedDayPaint);
        } else {
            CalendarDrawing.INSTANCE.day(canvas, showingMonth, day, inner, this.dayPaint);
        }
    }
    
    public measure(width: number, height: number, displayMetrics: DisplayMetrics): void {
        super.measure(width, height, displayMetrics);
        this.selectedDayPaint.textSize = this.dayPaint.textSize;
    }
    
    public onTap(day: DateAlone): void {
        this.selected.value = day;
    }
}

