// Generated by Khrysalis TypeScript converter
// File: views/ViewWithText.ext.actual.kt
// Package: com.lightningkite.khrysalis.views


const entityMap: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
    '/': '&#x2F;',
    '`': '&#x60;',
    '=': '&#x3D;',
    '\n': '<br/>'
};

function escapeHtml (s: string) {
    return String(s).replace(/[&<>"'`=\n\/]/g, function fromEntityMap (c) {
        return entityMap[c];
    });
}
export function setViewText(view: HTMLElement, text: string) {
    view.innerHTML = escapeHtml(text)
}