package com.lightningkite.khrysalis.web.layout.values

import com.lightningkite.khrysalis.utils.XmlNode
import com.lightningkite.khrysalis.utils.camelCase
import java.io.File
import com.lightningkite.khrysalis.typescript.safeJsIdentifier

fun getXmlStrings(file: File): Map<String, String> {
    return XmlNode.read(file, mapOf())
        .children
        .asSequence()
        .filter { it.name == "string" }
        .associate {
            (it.allAttributes["name"] ?: "noname") to it.element.textContent.replace("\\n", "\n").replace("\\t", "\t")
                .replace("\\'", "\'").replace("\\\"", "\"")
        }
}

fun translateXmlStringsToTypescript(file: File, out: Appendable) {
    out.appendLine("//Generated by Khrysalis")
    out.appendLine("//Should be stored in <application identifier> folder")
    out.appendLine("export class ResourcesStrings {")
    getXmlStrings(file)
        .forEach { (name, value) ->
            out.appendLine(
                "    static ${name.safeJsIdentifier()}: string = \"${
                    value.replace("\n", "\\n").replace("\t", "\\t").replace("\'", "\\'").replace("\"", "\\\"")
                }\";"
            )
        }
    out.appendLine("}")
}
