package com.lightningkite.khrysalis.web.layout.values

import com.lightningkite.khrysalis.utils.XmlNode
import com.lightningkite.khrysalis.utils.camelCase
import java.io.File

fun getXmlStrings(file: File): Map<String, String>{
    return XmlNode.read(file, mapOf())
        .children
        .asSequence()
        .filter { it.name == "string" }
        .associate {
            (it.allAttributes["name"] ?: "noname") to it.element.textContent.replace("\\n", "\n").replace("\\t", "\t")
        }
}

fun translateXmlStringsToTypescript(file: File, out: Appendable){
    out.appendln("//Generated by Khrysalis")
    out.appendln("//Should be stored in <application identifier> folder")
    out.appendln("export class ResourcesStrings {")
    getXmlStrings(file)
        .forEach { (name, value) ->
            out.appendln("    static $name: string = \"${value.replace("\n", "\\n").replace("\t", "\\t")}\";")
        }
    out.appendln("}")
}
