// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: location/GeoCoordinate.actual.kt
// Package: com.lightningkite.khrysalis.location
import { GeoCoordinate } from './GeoCoordinate.shared'

//! Declares com.lightningkite.khrysalis.location.distanceToMiles
export function ComLightningkiteKhrysalisLocationGeoCoordinateDistanceToMiles(this_DistanceToMiles: GeoCoordinate, other: GeoCoordinate): number{}

