// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: location/Geocoding.actual.kt
// Package: com.lightningkite.khrysalis.location
import { GeoCoordinate } from './GeoCoordinate.shared'
import { GeoAddress } from './GeoAddress.shared'
import { ViewDependency } from './../views/ViewDependency.actual'

//! Declares com.lightningkite.khrysalis.location.geocode
export function ComLightningkiteKhrysalisAndroidActivityAccessGeocode(this_Geocode: ViewDependency, coordinate: GeoCoordinate, onResult: (a: Array<GeoAddress>) => void){}

//! Declares com.lightningkite.khrysalis.location.geocode
export function ComLightningkiteKhrysalisAndroidActivityAccessGeocode(this_Geocode: ViewDependency, address: string, onResult: (a: Array<GeoAddress>) => void){}

