// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: views/draw/Paint.actual.kt
// Package: com.lightningkite.khrysalis.views.draw
// FQImport: android.graphics.Paint.FontMetrics.descent TS descent
// FQImport: android.graphics.Paint.FontMetrics.ascent TS ascent
// FQImport: fontMetrics TS getAndroidGraphicsPaintFontMetrics
// FQImport: android.graphics.Paint TS Paint
// FQImport: com.lightningkite.khrysalis.views.draw.<get-textHeight>.<anonymous>.it TS it

//! Declares com.lightningkite.khrysalis.views.draw.textHeight
export function getAndroidGraphicsPaintTextHeight(this_TextHeight: Paint): number { return ((it) => it.descent - it.ascent)(getAndroidGraphicsPaintFontMetrics(this_TextHeight)); }


