// Generated by Khrysalis TypeScript converter
// File: /home/josephivie/IdeaProjects/khrysalis/kotlin-compiler-plugin-typescript/testData/testImports.shared.kt
// Package: com.test.imports
// Imported FQ name: com.test.cursedclasses.A TS A
// Imported FQ name: com.test.cursedclasses.A.B TS B
// Imported FQ name: com.test.cursedclasses.A.B.C TS C
// Imported FQ name: com.test.cursedclasses.A.B.C.D.E TS ABCDE
// Imported FQ name: com.test.cursedclasses.A.B.C.D.E TS ABCDEDefaults
// Imported FQ name: com.test.cursedclasses.F.H TS FH
// Imported FQ name: com.test.cursedclasses.F.H.x TS x
// Imported FQ name: com.test.imports.main.thing TS thing
// Imported FQ name: com.test.variables.TestClass TS TestClass
// Imported FQ name: com.test.variables.extensionProperty TS getComTestVariablesTestClassExtensionProperty
// Imported FQ name: com.test.variables.extensionProperty TS setComTestVariablesTestClassExtensionProperty
// Imported FQ name: com.test.variables.topLevelHybrid TS getTopLevelHybrid
// Imported FQ name: com.test.variables.topLevelHybrid TS setTopLevelHybrid
// Imported FQ name: com.test.variables.topLevelReal TS getTopLevelReal
// Imported FQ name: com.test.variables.topLevelReal TS setTopLevelReal
// Imported FQ name: com.test.variables.topLevelVirtual TS getTopLevelVirtual
// Imported FQ name: com.test.variables.topLevelVirtual TS setTopLevelVirtual
// Imported FQ name: kotlin.Int TS Int
// Imported FQ name: kotlin.Unit TS Unit
// Imported FQ name: kotlin.io.println TS println
import { A, ABCDE, ABCDEDefaults, FH } from 'testCursedClasses.shared'
import { TestClass, getComTestVariablesTestClassExtensionProperty, getTopLevelHybrid, getTopLevelReal, getTopLevelVirtual, setComTestVariablesTestClassExtensionProperty, setTopLevelHybrid, setTopLevelReal, setTopLevelVirtual } from 'testVariables.shared'

export function main(){
    new A();
    new A.B();
    new A.B.C();
    new A.B.C.D();
    const testObj = new class Anon implements ABCDE {
        public static implementsInterfaceComTestCursedclassesABCDE = true;
        public constructor() {
            this.x = 0;
        }
        
        public readonly x: Int = 0;
        
        public test(): Unit { return ABCDEDefaults.test(this); }
    }();
    
    println(FH.INSTANCE.x);
    
    setTopLevelReal(getTopLevelReal().plus(1));
    setTopLevelVirtual(getTopLevelVirtual().plus(1));
    setTopLevelHybrid(getTopLevelHybrid().plus(1));
    
    const thing = new TestClass();
    
    setComTestVariablesTestClassExtensionProperty(thing, getComTestVariablesTestClassExtensionProperty(thing).plus(1));
}
