// Generated by Khrysalis TypeScript converter
// File: C:/Users/josep/Projects/khrysalis/kotlin-compiler-plugin-typescript/testData/testLoops.shared.kt
// Package: com.test.loops
// Imported FQ name: com.test.loops.main.i TS i
// Imported FQ name: com.test.loops.main.item TS item
// Imported FQ name: com.test.loops.main.key TS key
// Imported FQ name: com.test.loops.main.value TS value

export function main(){
    for (const item of [1, 2, 3, 4]) {
        console.log(item);
    }
    for (const toDestructure of new Map([[1, 2], [3, 4]]).entries()) {
        const key = toDestructure[0]
        const value = toDestructure[1]
        
        console.log(`${key}: ${value}`)
        
    }
    let i = 0;
    
    while(i < 4){
        i++;
        console.log(i);
    }
    label: while(i < 6){
        i++;
        console.log(i);
        break label;
    };
    do {
        i++;
        console.log(i);
    } while(i < 8)
}
