// Generated by Khrysalis TypeScript converter
// File: /home/josephivie/IdeaProjects/khrysalis/kotlin-compiler-plugin-typescript/testData/testCollections.shared.kt
// Package: com.test.collections
// Imported FQ name: com.test.collections.test.list TS list
// Imported FQ name: com.test.collections.test.pair TS pair
// Imported FQ name: kotlin.Int TS Int
// Imported FQ name: kotlin.Pair TS Pair
// Imported FQ name: kotlin.Pair.first TS first
// Imported FQ name: kotlin.Pair.second TS second
// Imported FQ name: kotlin.String TS String
// Imported FQ name: kotlin.collections.listOf TS listOf
// Imported FQ name: kotlin.io.println TS println
// Imported FQ name: kotlin.to TS KotlinAnyTo

export function test(){
    const list = listOf(1);
    
    println(list.get(0));
    
    const pair: Pair<Int, String> = KotlinAnyTo(3, "Three");
    
    println(pair.first);
    println(pair.second);
}
