// Generated by Khrysalis TypeScript converter
// File: /home/josephivie/IdeaProjects/khrysalis/kotlin-compiler-plugin-typescript/testData/testCursedClasses.shared.kt
// Package: com.test.cursedclasses
import { A, ABCDE, ABCDEDefaults, FG, FH } from './testCursedClasses.shared'

//! Declares com.test.cursedclasses.A
export class A {
    
    public static B = class B {
        
        public static C = class C {
            
            public static D = class D {
                public constructor() {
                }
                
                public static constructorkotlinInt(jank: number) {
                    let result = new D();
                    
                    console.log(jank)
                    
                    return result;
                }
                
            }
        }
    }
}

//! Declares com.test.cursedclasses.F
export interface F {
    
    
    
}
export class FDefaults {
}

//! Declares com.test.cursedclasses.main
export function main(){
    console.log("Clearly, we hate ourselves.");
    console.log(FH.INSTANCE.x);
    const thing = new class Anon implements ABCDE {
        public static implementsInterfaceComTestCursedclassesABCDE = true;
        public constructor() {
            this.hello = "Hello World!";
        }
        
        public readonly hello = "Hello World!";
        
        public test(): void { return ABCDEDefaults.test(this); }
    }();
    
    const other = new FG();
    
    
    new A();
    new A.B();
    new A.B.C();
    new A.B.C.D();
    return A.B.C.D.constructorkotlinInt(4);
}

//! Declares com.test.cursedclasses.A.B.C.D.E
export interface ABCDE {
    
    test(): void
}
export class ABCDEDefaults {
    public static test(this_Test: ABCDE){ return console.log("Hi!"); }
}
//! Declares com.test.cursedclasses.F.G
export class FG {
    
}
//! Declares com.test.cursedclasses.F.H
export class FH {
    private constructor() {
        this.x = 0;
    }
    public static INSTANCE = new FH();
    
    readonly x: number;
    
}

