// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: views/Colors.actual.kt
// Package: com.lightningkite.khrysalis.views
// FQImport: com.lightningkite.khrysalis.views.ColorValue SKIPPED due to same file
// FQImport: android.graphics.Color TS Color
// FQImport: com.lightningkite.khrysalis.views.colorAlpha.desiredAlpha TS desiredAlpha
// FQImport: android.graphics.Color.red TS red
// FQImport: android.graphics.Color.green TS green
// FQImport: android.graphics.Color.argb TS argb
// FQImport: android.graphics.Color.blue TS blue
// FQImport: com.lightningkite.khrysalis.views.ColorValue TS ColorValue

//! Declares com.lightningkite.khrysalis.views.ColorValue
export type ColorValue = number;
//! Declares com.lightningkite.khrysalis.views.ColorValue
export let ColorValue = Number;


//! Declares com.lightningkite.khrysalis.views.asColor
export function kotlinIntAsColor(this_: number): ColorValue{ return this_; }
//! Declares com.lightningkite.khrysalis.views.asColor
export function kotlinLongAsColor(this_: number): ColorValue{ return this_; }


//! Declares com.lightningkite.khrysalis.views.colorAlpha
export function kotlinIntColorAlpha(this_: ColorValue, desiredAlpha: number): ColorValue{ return Color.argb(desiredAlpha, Color.red(this_), Color.green(this_), Color.blue(this_)); }

