// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: views/EmptyView.actual.kt
// Package: com.lightningkite.khrysalis.views
// FQImport: android.view.View TS View
// FQImport: com.lightningkite.khrysalis.views.newEmptyView.dependency TS dependency
// FQImport: com.lightningkite.khrysalis.views.ViewDependency TS ViewDependency
// FQImport: com.lightningkite.khrysalis.android.ActivityAccess.context TS context
import { ViewDependency } from './ViewDependency.actual'

//! Declares com.lightningkite.khrysalis.views.newEmptyView
export function newEmptyView(dependency: ViewDependency): View{ return View.constructorandroidcontentContext(dependency.context); }

