// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: views/LinearLayout.actual.kt
// Package: com.lightningkite.khrysalis.views
import { AlignPair } from './geometry/Align.shared'

//! Declares com.lightningkite.khrysalis.views.params
export function AndroidWidgetLinearLayoutParams(this_Params: LinearLayout, sizeX: number = 0, sizeY: number = 0, marginStart: number = 0, marginEnd: number = 0, marginTop: number = 0, marginBottom: number = 0, gravity: AlignPair = AlignPair.Companion.INSTANCE.center, weight: number = 0f): LinearLayout.LayoutParams{}

