// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: views/ResourceTypes.actual.kt
// Package: com.lightningkite.khrysalis.views

//! Declares com.lightningkite.khrysalis.views.StringResource
export type StringResource = number;
//! Declares com.lightningkite.khrysalis.views.StringResource
export let StringResource = Number;

//! Declares com.lightningkite.khrysalis.views.ColorResource
export type ColorResource = number;
//! Declares com.lightningkite.khrysalis.views.ColorResource
export let ColorResource = Number;

//! Declares com.lightningkite.khrysalis.views.DrawableResource
export type DrawableResource = number;
//! Declares com.lightningkite.khrysalis.views.DrawableResource
export let DrawableResource = Number;


