// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: views/SelectDateRangeMonthCVD.shared.kt
// Package: com.lightningkite.khrysalis.views
import { StandardObservableProperty } from './../observables/StandardObservableProperty.shared'
import { MutableObservableProperty } from './../observables/MutableObservableProperty.shared'
import { DateAlone } from './../time/DateAlone.actual'
import { MonthCVD } from './MonthCVD.shared'

//! Declares com.lightningkite.khrysalis.views.SelectDateRangeMonthCVD
export class SelectDateRangeMonthCVD extends MonthCVD {
    constructor() { super(); }
    public generateAccessibilityView(): (View | null){ return null; }
    
    public draggingStart: Boolean = true;
    
    public start: MutableObservableProperty<(DateAlone | null)> = new StandardObservableProperty(null, undefined);
    
    public endInclusive: MutableObservableProperty<(DateAlone | null)> = new StandardObservableProperty(null, undefined);
    
    
    
    public readonly selectedDayPaint: Paint = Paint.constructor();
    
    public readonly selectedPaint: Paint = Paint.constructor();
    
    
    public measure(width: number, height: number, displayMetrics: DisplayMetrics){
        .measure(width, height, displayMetrics);
        setAndroidGraphicsPaintTextSize(selectedDayPaint, getAndroidGraphicsPaintTextSize(dayPaint));
    }
    
    public readonly drawDay_dateAlone: DateAlone = new DateAlone(0, 0, 0);
    
    public drawDay(
        canvas: Canvas,
        showingMonth: DateAlone,
        day: DateAlone,
        displayMetrics: DisplayMetrics,
        outer: RectF,
        inner: RectF
    ){
        if(day.equals(start.value) && (day.equals(endInclusive.value) || endInclusive.value.equals(null))){
            CalendarDrawing.INSTANCE.dayBackground(canvas, inner, this.selectedPaint);
            CalendarDrawing.INSTANCE.day(canvas, showingMonth, day, inner, this.selectedDayPaint);
        }else if(day.equals(start.value)){
            CalendarDrawing.INSTANCE.dayBackgroundStart(canvas, inner, outer, this.selectedPaint);
            CalendarDrawing.INSTANCE.day(canvas, showingMonth, day, inner, this.selectedDayPaint);
        }else if(day.equals(endInclusive.value)){
            CalendarDrawing.INSTANCE.dayBackgroundEnd(canvas, inner, outer, this.selectedPaint);
            CalendarDrawing.INSTANCE.day(canvas, showingMonth, day, inner, this.selectedDayPaint);
        }else if(day.comparable > (start.value?.this.comparable ?: Int.Companion.INSTANCE.MAX_VALUE) && day.comparable < (endInclusive.value?.this.comparable ?: Int.Companion.INSTANCE.MIN_VALUE)){
            CalendarDrawing.INSTANCE.dayBackgroundMid(canvas, inner, outer, this.selectedPaint);
            CalendarDrawing.INSTANCE.day(canvas, showingMonth, day, inner, this.selectedDayPaint);
        }else {
            CalendarDrawing.INSTANCE.day(canvas, showingMonth, day, inner, this.dayPaint);
        };
    }
    
    
    private startedDraggingOn: (DateAlone | null) = null;
    
    
    public onTap(day: DateAlone){
        if(!(start.value.equals(null)) && start.value.equals(endInclusive.value) && day.comparable > start.value!!.comparable){
            endInclusive.value = day;
        } else {
            start.value = day;
            endInclusive.value = day;
        }
    }
    
    public onTouchDown(day: DateAlone): Boolean{
        if(!(day.equals(start.value)) && !(day.equals(endInclusive.value))){
            return false;
        }
        this.startedDraggingOn = day;
        //If on start/end - drag
        //If after, extend
        //If before, extend
        //If middle, collapse all
        const startValue = start.value;
        
        const endInclusiveValue = endInclusive.value;
        
        
        if(startValue.equals(null) || endInclusiveValue.equals(null)){
            start.value = day;
            endInclusive.value = day;
            this.draggingStart = false;
        }else if(day.equals(endInclusiveValue)){
            this.draggingStart = false;
        }else if(day.equals(startValue)){
            this.draggingStart = true;
        }else if(day.comparable > endInclusiveValue!!.comparable && startValue.equals(endInclusiveValue)){
            endInclusive.value = day;
            this.draggingStart = false;
        }else {
            start.value = day;
            endInclusive.value = day;
            this.draggingStart = false;
        };
        return true;
    }
    
    public onTouchMove(day: DateAlone): Boolean{
        const startValue = start.value;
        
        const endInclusiveValue = endInclusive.value;
        
        if(startValue.equals(null) || endInclusiveValue.equals(null)){
        }else if(this.draggingStart && day.comparable > endInclusiveValue!!.comparable){
            start.value = endInclusive.value;
            endInclusive.value = day;
            this.draggingStart = false;
            return true;
        }else if(this.draggingStart.not() && day.comparable < startValue!!.comparable){
            endInclusive.value = start.value;
            start.value = day;
            this.draggingStart = true;
            return true;
        };
        
        const obs: MutableObservableProperty<(DateAlone | null)> = (() => {if (this.draggingStart) {
                    return this.start
                }
                else {
                    return this.endInclusive
                }
        })();
        
        obs.value = day;
        return true;
    }
    
    public onTouchUp(day: DateAlone): Boolean{
        onTouchMove(day);
        return true;
    }
}

