// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: views/ViewDependency.actual.kt
// Package: com.lightningkite.khrysalis.views
import { ViewDependency } from './ViewDependency.actual'
import { ColorResource, StringResource } from './ResourceTypes.actual'
import { Image } from './../Image.shared'
import { GeoCoordinate } from './../location/GeoCoordinate.shared'

//! Declares com.lightningkite.khrysalis.views.ViewDependency
export type ViewDependency = ActivityAccess;
//! Declares com.lightningkite.khrysalis.views.ViewDependency
export let ViewDependency = ActivityAccess;


//! Declares com.lightningkite.khrysalis.views.getString
export function ComLightningkiteKhrysalisAndroidActivityAccessGetString(this_GetString: ViewDependency, resource: StringResource): string{}
//! Declares com.lightningkite.khrysalis.views.getColor
export function ComLightningkiteKhrysalisAndroidActivityAccessGetColor(this_GetColor: ViewDependency, resource: ColorResource): number{}
//! Declares com.lightningkite.khrysalis.views.displayMetrics
export function getComLightningkiteKhrysalisAndroidActivityAccessDisplayMetrics(this_DisplayMetrics: ViewDependency): DisplayMetrics {}


//! Declares com.lightningkite.khrysalis.views.share
export function ComLightningkiteKhrysalisAndroidActivityAccessShare(this_Share: ViewDependency, shareTitle: string, message: (string | null) = null, url: (string | null) = null, image: (Image | null) = null){}

//! Declares com.lightningkite.khrysalis.views.openUrl
export function ComLightningkiteKhrysalisAndroidActivityAccessOpenUrl(this_OpenUrl: ViewDependency, url: string): Boolean{}

//! Declares com.lightningkite.khrysalis.views.openAndroidAppOrStore
export function ComLightningkiteKhrysalisAndroidActivityAccessOpenAndroidAppOrStore(this_OpenAndroidAppOrStore: ViewDependency, packageName: string){}

//! Declares com.lightningkite.khrysalis.views.openIosStore
export function ComLightningkiteKhrysalisAndroidActivityAccessOpenIosStore(this_OpenIosStore: ViewDependency, numberId: string){}

//! Declares com.lightningkite.khrysalis.views.openMap
export function ComLightningkiteKhrysalisAndroidActivityAccessOpenMap(this_OpenMap: ViewDependency, coordinate: GeoCoordinate, label: (string | null) = null, zoom: (number | null) = null){}

//! Declares com.lightningkite.khrysalis.views.openEvent
export function ComLightningkiteKhrysalisAndroidActivityAccessOpenEvent(this_OpenEvent: ViewDependency, title: string, description: string, location: string, start: Date, end: Date){}

//! Declares com.lightningkite.khrysalis.views.requestImagesGallery
export function ComLightningkiteKhrysalisAndroidActivityAccessRequestImagesGallery(this_RequestImagesGallery: ViewDependency, callback: (a: Array<Uri>) => void){}

//! Declares com.lightningkite.khrysalis.views.requestImageGallery
export function ComLightningkiteKhrysalisAndroidActivityAccessRequestImageGallery(this_RequestImageGallery: ViewDependency, callback: (a: Uri) => void){}

//! Declares com.lightningkite.khrysalis.views.requestImageCamera
export function ComLightningkiteKhrysalisAndroidActivityAccessRequestImageCamera(this_RequestImageCamera: ViewDependency, front: Boolean = false, callback: (a: Uri) => void){}


//! Declares com.lightningkite.khrysalis.views.downloadDrawable
export function ComLightningkiteKhrysalisAndroidActivityAccessDownloadDrawable(this_DownloadDrawable: ViewDependency, url: string, width: (number | null) = null, height: (number | null) = null, onResult: (a: (Drawable | null)) => void){}

//! Declares com.lightningkite.khrysalis.views.checkedDrawable
export function ComLightningkiteKhrysalisAndroidActivityAccessCheckedDrawable(this_CheckedDrawable: ViewDependency, checked: Drawable, normal: Drawable){}

//! Declares com.lightningkite.khrysalis.views.setSizeDrawable
export function ComLightningkiteKhrysalisAndroidActivityAccessSetSizeDrawable(this_SetSizeDrawable: ViewDependency, drawable: Drawable, width: number, height: number): Drawable{}

