// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: views/View.ext.actual.kt
// Package: com.lightningkite.khrysalis.views
import { ColorResource } from './ResourceTypes.actual'

//! Declares com.lightningkite.khrysalis.views.backgroundDrawable
export function getAndroidViewViewBackgroundDrawable(this_BackgroundDrawable: View): (Drawable | null) {}
export function setAndroidViewViewBackgroundDrawable(this_BackgroundDrawable1: View, value: (Drawable | null)) {}


//! Declares com.lightningkite.khrysalis.views.backgroundResource
export function getAndroidViewViewBackgroundResource(this_BackgroundResource: View): number {}
export function setAndroidViewViewBackgroundResource(this_BackgroundResource1: View, value: number) {}



//! Declares com.lightningkite.khrysalis.views.onClick
export function AndroidViewViewOnClick(this_OnClick: View, action: () => void){}

//! Declares com.lightningkite.khrysalis.views.onClick
export function AndroidViewViewOnClick(this_OnClick: View, disabledMilliseconds: number, action: () => void){}

//! Declares com.lightningkite.khrysalis.views.onLongClick
export function AndroidViewViewOnLongClick(this_OnLongClick: View, action: () => void){}


//! Declares com.lightningkite.khrysalis.views.setBackgroundColorResource
export function AndroidViewViewSetBackgroundColorResource(this_SetBackgroundColorResource: View, color: ColorResource){}

