// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: observables/TransformedMutableObservableProperty2.shared.kt
// Package: com.lightningkite.khrysalis.observables
import { Observable } from 'rxjs'
import { map as rxMap } from 'rxjs/operators'
import { MutableObservableProperty } from './MutableObservableProperty.shared'

//! Declares com.lightningkite.khrysalis.observables.TransformedMutableObservableProperty2
export class TransformedMutableObservableProperty2<A, B> extends MutableObservableProperty<B> {
    public readonly basedOn: MutableObservableProperty<A>;
    public readonly read:  ((a: A) => B);
    public readonly write:  ((a: A, b: B) => A);
    public constructor(basedOn: MutableObservableProperty<A>, read:  ((a: A) => B), write:  ((a: A, b: B) => A)) {
        super();
        this.basedOn = basedOn;
        this.read = read;
        this.write = write;
    }
    
    public update(): void {
        this.basedOn.update();
    }
    
    //! Declares com.lightningkite.khrysalis.observables.TransformedMutableObservableProperty2.value
    public get value(): B {
        return this.read(this.basedOn.value);
    }
    public set value(value: B) {
        this.basedOn.value = this.write(this.basedOn.value, value);
    }
    
    //! Declares com.lightningkite.khrysalis.observables.TransformedMutableObservableProperty2.onChange
    public get onChange(): Observable<B> {
        const readCopy = this.read;
        
        return this.basedOn.onChange.pipe(rxMap((it: A): B => readCopy(it)));
    }
    
}

//! Declares com.lightningkite.khrysalis.observables.mapWithExisting>com.lightningkite.khrysalis.observables.MutableObservableProperty<kotlin.Any>
export function xMutableObservablePropertyMapWithExisting<T, B>(this_: MutableObservableProperty<T>, read:  ((a: T) => B), write:  ((a: T, b: B) => T)): MutableObservableProperty<B> {
    return new TransformedMutableObservableProperty2<T, B>(this_, read, write);
}

