// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: testImports.shared.kt
// Package: com.test.imports
import { TestClass, getTopLevelHybrid, getTopLevelReal, getTopLevelVirtual, setTopLevelHybrid, setTopLevelReal, setTopLevelVirtual, xTestClassExtensionPropertyGet, xTestClassExtensionPropertySet } from './testVariables.shared'
import { A, F } from './testCursedClasses.shared'
import { sayDelicious } from './actualExample'

//! Declares com.test.imports.main
export function main(): void {
    A();
    new A.B(undefined);
    new A.B.C();
    new A.B.C.D();
    const testObj = new class Anon implements A.B.C.D.E {
        public static implementsInterfaceComTestCursedclassesABCDE = true;
        public constructor() {
            this.x = 0;
        }
        
        public readonly x: Int;
        
        public test(): Unit { return A.B.C.D.EDefaults.test(this); }
    }();
    
    println(F.H.INSTANCE.x);
    
    setTopLevelReal(getTopLevelReal().plus(1));
    setTopLevelVirtual(getTopLevelVirtual().plus(1));
    setTopLevelHybrid(getTopLevelHybrid().plus(1));
    
    const thing = new TestClass();
    
    xTestClassExtensionPropertySet(thing, xTestClassExtensionPropertyGet(thing).plus(1));
    
    sayDelicious();
    sayDeliciousFromOtherLib();
}
