// Generated by Khrysalis TypeScript converter
// File: rx/RxExtensions.actual.kt
// Package: com.lightningkite.khrysalis.rx
import { finalize as rxFinalize} from 'rxjs/operators'
import { MutableObservableProperty } from '../observables/MutableObservableProperty.shared'
import { doOnSubscribe } from '../Kotlin'
import { Observable} from 'rxjs'
import { post } from '../delay.actual'
//! Declares com.lightningkite.khrysalis.rx.working
export function ioReactivexSingleWorking<Element extends any>(this_Working: Observable<Element>, observable: MutableObservableProperty<Boolean>): Observable<Element>{
    return rxFinalize(() => post(() => observable.value = false))(doOnSubscribe(this_Working, (it) => post(() => observable.value = true))) as Observable<Element>;
}

