// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: time/DateAlone.shared.kt
// Package: com.lightningkite.khrysalis.time
import { dateFrom } from './Date.actual'
import { DateAlone } from './DateAlone.actual'
import { JavaUtilDateFormat } from './TimeAlone.shared'
import { ClockPartSize } from './ClockPartSize.shared'

//! Declares com.lightningkite.khrysalis.time.set
export function ComLightningkiteKhrysalisTimeDateAloneSet(this_Set: DateAlone, other: DateAlone): DateAlone{
    this_Set.year = other.year;
    this_Set.month = other.month;
    this_Set.day = other.day;
    return this_Set;
}

//! Declares com.lightningkite.khrysalis.time.format
export function ComLightningkiteKhrysalisTimeDateAloneFormat(this_Format: DateAlone, clockPartSize: ClockPartSize): string{ return JavaUtilDateFormat(dateFrom(this_Format, TimeAlone.Companion.INSTANCE.noon, undefined), clockPartSize, ClockPartSize.None); }

