// Generated by Khrysalis TypeScript converter
// File: net/HttpClient.actual.kt
// Package: com.lightningkite.khrysalis.net
import {from, Observable, using} from 'rxjs'
import {ConnectedWebSocket} from "./ConnectedWebSocket.actual";

//! Declares com.lightningkite.khrysalis.net.HttpClient
export class HttpClient {
    public static INSTANCE = new HttpClient();

    public readonly GET = "GET";
    public readonly POST = "POST";
    public readonly PUT = "PUT";
    public readonly PATCH = "PATCH";
    public readonly DELETE = "DELETE";

    call(
        url: string,
        method: string = HttpClient.INSTANCE.GET,
        headers: Map<string, string> = new Map([]),
        body: (BodyInit | null) = null
    ): Observable<Response> {
        return from(fetch(url, {
            body: body,
            cache: "no-cache",
            credentials: "omit",
            headers: Object.fromEntries(headers),
            method: method
        }))
    }
    
    webSocket(url: string): Observable<ConnectedWebSocket>{
        return using<ConnectedWebSocket>(
            ()=> {
                const out = new ConnectedWebSocket(url)
                // out.underlyingSocket =
                return out
            },
            (r) => (r as ConnectedWebSocket).ownConnection
        )
    }
}
