// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: net/WebSocketFrame.actual.kt
// Package: com.lightningkite.khrysalis.net

//! Declares com.lightningkite.khrysalis.net.WebSocketFrame
export class WebSocketFrame {
    public readonly binary: (Int8Array | null);
    public readonly text: (string | null);
    public constructor(binary: (Int8Array | null) = null, text: (string | null) = null) {
        this.binary = binary;
        this.text = text;
    }
    
    public toString(): string {
        return this.text ?? (()=>{
                let temp_100;
                if ((temp_100 = this.binary) !== null) { 
                    return `<Binary data length ${temp_100.length}`;
                } else { return null }
        })() ?? "<Empty Frame>";
    }
}

