// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: views/ViewGenerator.shared.kt
// Package: com.lightningkite.khrysalis.views
import Foundation

public class ViewGenerator {
    public init() {
    }
    
    public var title: String { get { TODO() } }
    
    public func generate(dependency: ViewDependency) -> View { TODO() }
    
    public class Default : ViewGenerator {
        override public init() {
            super.init()
        }
        
        override public var title: String {
            get { return "Empty" }
        }
        
        override public func generate(dependency: ViewDependency) -> View { return newEmptyView(dependency: dependency) }
        
    }
}


