// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: observables/ObservableProperty.shared.kt
// Package: com.lightningkite.khrysalis.observables
// FQImport: com.lightningkite.khrysalis.observables.ObservableProperty.T TS T
// FQImport: com.lightningkite.khrysalis.Box TS Box
import { Observable } from 'rxjs'

//! Declares com.lightningkite.khrysalis.observables.ObservableProperty
export abstract class ObservableProperty<T> {
    
    public readonly value: T;
    
    public readonly onChange: Observable<Box<T>>;
    
}


