// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: observables/StandardObservableProperty.shared.kt
// Package: com.lightningkite.khrysalis.observables
import { Box, boxWrap } from './../Box.actual'
import { MutableObservableProperty } from './MutableObservableProperty.shared'

//! Declares com.lightningkite.khrysalis.observables.StandardObservableProperty
export class StandardObservableProperty<T> extends MutableObservableProperty<any> {
    public underlyingValue: T;
    public readonly onChange: Subject<Box<T>>;
    public constructor( underlyingValue: T, override  onChange: Subject<Box<T>> = PublishSubject.create()) {
        super();
        this.underlyingValue = underlyingValue;
        this.onChange = onChange;
    }
    
    //! Declares com.lightningkite.khrysalis.observables.StandardObservableProperty.value
    public get value(): T { return this.underlyingValue; }
    public set value(value: T) {
        this.underlyingValue = value;
        onChange.onNext(boxWrap(value));
    }
    
    
    public update(){
        onChange.onNext(boxWrap(this.value));
    }
}

