package com.lightningkite.khrysalis.time

import java.time.*

fun ZonedDateTime.plusYears(amount: Int) = plusYears(amount.toLong())
fun ZonedDateTime.plusMonths(amount: Int) = plusMonths(amount.toLong())
fun ZonedDateTime.plusDays(amount: Int) = plusDays(amount.toLong())
fun ZonedDateTime.plusHours(amount: Int) = plusHours(amount.toLong())
fun ZonedDateTime.plusMinutes(amount: Int) = plusMinutes(amount.toLong())
fun ZonedDateTime.plusSeconds(amount: Int) = plusSeconds(amount.toLong())
fun ZonedDateTime.plusNanos(amount: Int) = plusNanos(amount.toLong())
fun LocalDateTime.plusYears(amount: Int) = plusYears(amount.toLong())
fun LocalDateTime.plusMonths(amount: Int) = plusMonths(amount.toLong())
fun LocalDateTime.plusDays(amount: Int) = plusDays(amount.toLong())
fun LocalDateTime.plusHours(amount: Int) = plusHours(amount.toLong())
fun LocalDateTime.plusMinutes(amount: Int) = plusMinutes(amount.toLong())
fun LocalDateTime.plusSeconds(amount: Int) = plusSeconds(amount.toLong())
fun LocalDateTime.plusNanos(amount: Int) = plusNanos(amount.toLong())
fun LocalDate.plusYears(amount: Int) = plusYears(amount.toLong())
fun LocalDate.plusMonths(amount: Int) = plusMonths(amount.toLong())
fun LocalDate.plusDays(amount: Int) = plusDays(amount.toLong())
fun LocalTime.plusHours(amount: Int) = plusHours(amount.toLong())
fun LocalTime.plusMinutes(amount: Int) = plusMinutes(amount.toLong())
fun LocalTime.plusSeconds(amount: Int) = plusSeconds(amount.toLong())
fun LocalTime.plusNanos(amount: Int) = plusNanos(amount.toLong())
fun ZonedDateTime.minusYears(amount: Int) = minusYears(amount.toLong())
fun ZonedDateTime.minusMonths(amount: Int) = minusMonths(amount.toLong())
fun ZonedDateTime.minusDays(amount: Int) = minusDays(amount.toLong())
fun ZonedDateTime.minusHours(amount: Int) = minusHours(amount.toLong())
fun ZonedDateTime.minusMinutes(amount: Int) = minusMinutes(amount.toLong())
fun ZonedDateTime.minusSeconds(amount: Int) = minusSeconds(amount.toLong())
fun ZonedDateTime.minusNanos(amount: Int) = minusNanos(amount.toLong())
fun LocalDateTime.minusYears(amount: Int) = minusYears(amount.toLong())
fun LocalDateTime.minusMonths(amount: Int) = minusMonths(amount.toLong())
fun LocalDateTime.minusDays(amount: Int) = minusDays(amount.toLong())
fun LocalDateTime.minusHours(amount: Int) = minusHours(amount.toLong())
fun LocalDateTime.minusMinutes(amount: Int) = minusMinutes(amount.toLong())
fun LocalDateTime.minusSeconds(amount: Int) = minusSeconds(amount.toLong())
fun LocalDateTime.minusNanos(amount: Int) = minusNanos(amount.toLong())
fun LocalDate.minusYears(amount: Int) = minusYears(amount.toLong())
fun LocalDate.minusMonths(amount: Int) = minusMonths(amount.toLong())
fun LocalDate.minusDays(amount: Int) = minusDays(amount.toLong())
fun LocalTime.minusHours(amount: Int) = minusHours(amount.toLong())
fun LocalTime.minusMinutes(amount: Int) = minusMinutes(amount.toLong())
fun LocalTime.minusSeconds(amount: Int) = minusSeconds(amount.toLong())
fun LocalTime.minusNanos(amount: Int) = minusNanos(amount.toLong())