// Generated by Khrysalis TypeScript converter
// File: observables/binding/CompoundButton.binding.actual.kt
// Package: com.lightningkite.khrysalis.observables.binding
import { MutableObservableProperty } from '../MutableObservableProperty.shared'

//! Declares com.lightningkite.khrysalis.observables.binding.bindSelect>android.widget.CompoundButton
export function androidWidgetCompoundButtonBindSelect<T>(this_: HTMLElement, value: T, observable: MutableObservableProperty<T>): void {
}


//! Declares com.lightningkite.khrysalis.observables.binding.bindSelectNullable>android.widget.CompoundButton
export function androidWidgetCompoundButtonBindSelectNullable<T>(this_: HTMLElement, value: T, observable: MutableObservableProperty<(T | null)>): void {
}




//! Declares com.lightningkite.khrysalis.observables.binding.bindSelectInvert>android.widget.CompoundButton
export function androidWidgetCompoundButtonBindSelectInvert<T>(this_: HTMLElement, value: T, observable: MutableObservableProperty<(T | null)>): void {
}

//! Declares com.lightningkite.khrysalis.observables.binding.bind>android.widget.CompoundButton
export function androidWidgetCompoundButtonBind(this_: HTMLElement, observable: MutableObservableProperty<boolean>): void {
}


