// Generated by Khrysalis TypeScript converter
// File: observables/binding/TabLayout.binding.actual.kt
// Package: com.lightningkite.khrysalis.observables.binding
import {comLightningkiteKhrysalisObservablesObservablePropertySubscribeBy} from '../ObservableProperty.ext.shared'
import {getAndroidViewViewRemoved, ioReactivexDisposablesDisposableUntil} from '../../rx/DisposeCondition.actual'
import {MutableObservableProperty} from '../MutableObservableProperty.shared'

//! Declares com.lightningkite.khrysalis.observables.binding.bind>com.google.android.material.tabs.TabLayout
export function comGoogleAndroidMaterialTabsTabLayoutBind(this_: HTMLDivElement, tabs: Array<string>, selected: MutableObservableProperty<number>): void {
    const myName = this.id ?? "tabLayout";

    const selectedIndicator = document.createElement("div");
    selectedIndicator.classList.add("khrysalis-tab-indicator");
    this_.appendChild(selectedIndicator);

    const tabList = document.createElement("div");
    tabList.classList.add("khrysalis-tab-list");
    this_.appendChild(tabList);

    let index = 0;
    for (const tab of tabs) {
        const myIndex = index;
        const tabElement = document.createElement("label");
        tabElement.innerText = tab;
        tabElement.classList.add("khrysalis-tab");
        tabElement.htmlFor = myName + myIndex.toString();
        tabList.appendChild(tabElement);
        const radio = document.createElement("input");
        radio.type = "radio";
        radio.id = myName + myIndex.toString();
        radio.name = myName;
        radio.onchange = (ev) => {
            selected.value = myIndex;
        }
        tabList.appendChild(radio);
        index++;
    }

    ioReactivexDisposablesDisposableUntil(comLightningkiteKhrysalisObservablesObservablePropertySubscribeBy(selected, undefined, undefined, (index) => {
        (tabList.children.item(index * 2 + 1) as HTMLInputElement).checked = true;
        const tab = tabList.children.item(index * 2) as HTMLElement;
        selectedIndicator.style.left = tab.offsetLeft.toString() + "px";
        selectedIndicator.style.width = tab.offsetWidth.toString() + "px";
    }), getAndroidViewViewRemoved(this_));
}

