// Generated by Khrysalis TypeScript converter
// File: observables/binding/ViewPager.binding.actual.kt
// Package: com.lightningkite.khrysalis.observables.binding
import { comLightningkiteKhrysalisObservablesObservablePropertySubscribeBy } from '../ObservableProperty.ext.shared'
import { getAndroidViewViewRemoved, ioReactivexDisposablesDisposableUntil } from '../../rx/DisposeCondition.actual'
import { StandardObservableProperty } from '../StandardObservableProperty.shared'
import { ObservableProperty } from '../ObservableProperty.shared'
import { comLightningkiteKhrysalisObservablesObservablePropertyMap } from '../TransformedObservableProperty.shared'
import { MutableObservableProperty } from '../MutableObservableProperty.shared'

//! Declares com.lightningkite.khrysalis.observables.binding.bind>androidx.viewpager.widget.ViewPager
export function androidxViewpagerWidgetViewPagerBindStatic<T>(this_: HTMLDivElement, items: Array<T>, showIndex: MutableObservableProperty<number> = new StandardObservableProperty(0, undefined), makeView: (a: T) => HTMLElement): void {

}

//! Declares com.lightningkite.khrysalis.observables.binding.bind>androidx.viewpager.widget.ViewPager
export function androidxViewpagerWidgetViewPagerBind<T>(this_: HTMLDivElement, items: ObservableProperty<Array<T>>, _default: T, showIndex: MutableObservableProperty<number> = new StandardObservableProperty(0, undefined), makeView: (a: ObservableProperty<T>) => HTMLElement): void {
}

