// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: observables/binding/DateButton.binding.actual.kt
// Package: com.lightningkite.khrysalis.observables.binding
import { MutableObservableProperty } from './../MutableObservableProperty.shared'
import { DateAlone } from './../../time/DateAlone.actual'
import { TimeAlone } from './../../time/TimeAlone.actual'

//! Declares com.lightningkite.khrysalis.observables.binding.bind
export function ComLightningkiteKhrysalisViewsAndroidDateButtonBind(this_Bind: DateButton, date: MutableObservableProperty<Date>){}


//! Declares com.lightningkite.khrysalis.observables.binding.bind
export function ComLightningkiteKhrysalisViewsAndroidTimeButtonBind(this_Bind: TimeButton, date: MutableObservableProperty<Date>, minuteInterval: number = 1){}


//! Declares com.lightningkite.khrysalis.observables.binding.bindDateAlone
export function ComLightningkiteKhrysalisViewsAndroidDateButtonBindDateAlone(this_BindDateAlone: DateButton, date: MutableObservableProperty<DateAlone>){}


//! Declares com.lightningkite.khrysalis.observables.binding.bindTimeAlone
export function ComLightningkiteKhrysalisViewsAndroidTimeButtonBindTimeAlone(this_BindTimeAlone: TimeButton, date: MutableObservableProperty<TimeAlone>, minuteInterval: number = 1){}

