// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: observables/binding/EditText.binding.actual.kt
// Package: com.lightningkite.khrysalis.observables.binding
import { MutableObservableProperty } from './../MutableObservableProperty.shared'

//! Declares com.lightningkite.khrysalis.observables.binding.bindString
export function AndroidWidgetEditTextBindString(this_BindString: EditText, observable: MutableObservableProperty<string>){}

//! Declares com.lightningkite.khrysalis.observables.binding.bindInteger
export function AndroidWidgetEditTextBindInteger(this_BindInteger: EditText, observable: MutableObservableProperty<number>){}



//! Declares com.lightningkite.khrysalis.observables.binding.bindDouble
export function AndroidWidgetEditTextBindDouble(this_BindDouble: EditText, observable: MutableObservableProperty<number>){}

