// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: observables/binding/TabLayout.binding.actual.kt
// Package: com.lightningkite.khrysalis.observables.binding
import { MutableObservableProperty } from './../MutableObservableProperty.shared'

//! Declares com.lightningkite.khrysalis.observables.binding.bind
export function ComGoogleAndroidMaterialTabsTabLayoutBind(this_Bind: TabLayout, tabs: Array<string>, selected: MutableObservableProperty<number>){}

