// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: observables/binding/ViewFlipper.binding.actual.kt
// Package: com.lightningkite.khrysalis.observables.binding
// FQImport: childCount TS getAndroidWidgetViewFlipperChildCount
// FQImport: kotlin.Boolean TS Boolean
// FQImport: com.lightningkite.khrysalis.observables.binding.bindLoading.<anonymous>.it TS it
// FQImport: android.graphics.LightingColorFilter TS LightingColorFilter
// FQImport: interpolator TS setAndroidViewAnimationAlphaAnimationInterpolator
// FQImport: inAnimation TS getAndroidWidgetViewFlipperInAnimation
// FQImport: android.content.res.Resources.getColor TS getColor
// FQImport: android.widget.ViewFlipper.addView TS addView
// FQImport: android.widget.ViewFlipper TS ViewFlipper
// FQImport: com.lightningkite.khrysalis.observables.subscribeBy TS comLightningkiteKhrysalisObservablesObservablePropertySubscribeBy
// FQImport: com.lightningkite.khrysalis.views.ColorResource TS ColorResource
// FQImport: com.lightningkite.khrysalis.observables.binding.bindLoading.color TS color
// FQImport: indeterminateDrawable TS getAndroidWidgetProgressBarIndeterminateDrawable
// FQImport: com.lightningkite.khrysalis.observables.binding.bindLoading.spinner TS spinner
// FQImport: android.widget.ProgressBar TS ProgressBar
// FQImport: colorFilter TS setAndroidGraphicsDrawableDrawableColorFilter
// FQImport: duration TS setAndroidViewAnimationAlphaAnimationDuration
// FQImport: android.view.animation.AlphaAnimation TS AlphaAnimation
// FQImport: com.lightningkite.khrysalis.observables.binding.bindLoading.<anonymous>.color TS color
// FQImport: com.lightningkite.khrysalis.observables.binding.bindLoading.loading TS loading
// FQImport: resources TS getAndroidWidgetViewFlipperResources
// FQImport: com.lightningkite.khrysalis.rx.until TS ioReactivexDisposablesDisposableUntil
// FQImport: android.view.Gravity TS Gravity
// FQImport: android.view.Gravity.CENTER TS CENTER
// FQImport: displayedChild TS setAndroidWidgetViewFlipperDisplayedChild
// FQImport: inAnimation TS setAndroidWidgetViewFlipperInAnimation
// FQImport: android.view.animation.LinearInterpolator TS LinearInterpolator
// FQImport: android.view.ViewGroup.LayoutParams.WRAP_CONTENT TS WRAP_CONTENT
// FQImport: com.lightningkite.khrysalis.observables.ObservableProperty TS ObservableProperty
// FQImport: outAnimation TS getAndroidWidgetViewFlipperOutAnimation
// FQImport: android.widget.FrameLayout TS FrameLayout
// FQImport: outAnimation TS setAndroidWidgetViewFlipperOutAnimation
// FQImport: com.lightningkite.khrysalis.observables.binding.bindLoading.<anonymous>.colorValue TS colorValue
// FQImport: context TS getAndroidWidgetViewFlipperContext
// FQImport: com.lightningkite.khrysalis.rx.removed TS getAndroidViewViewRemoved
import { comLightningkiteKhrysalisObservablesObservablePropertySubscribeBy } from './../ObservableProperty.ext.shared'
import { getAndroidViewViewRemoved, ioReactivexDisposablesDisposableUntil } from './../../rx/DisposeCondition.actual'
import { ObservableProperty } from './../ObservableProperty.shared'
import { also } from 'khrysalis/dist/Kotlin'
import { ColorResource } from './../../views/ResourceTypes.actual'

//! Declares com.lightningkite.khrysalis.observables.binding.bindLoading
export function androidWidgetViewFlipperBindLoading(this_BindLoading: ViewFlipper, loading: ObservableProperty<Boolean>, color: (ColorResource | null) = null){
    getAndroidWidgetViewFlipperInAnimation(this_BindLoading).equals(null) ? setAndroidWidgetViewFlipperInAnimation(this_BindLoading, also(AlphaAnimation.constructorkotlinFloat, kotlinFloat(0f, 1f), (this_) => {
                setAndroidViewAnimationAlphaAnimationDuration(this_, 250);
                setAndroidViewAnimationAlphaAnimationInterpolator(this_, LinearInterpolator.constructor());
    })) : 
    getAndroidWidgetViewFlipperOutAnimation(this_BindLoading).equals(null) ? setAndroidWidgetViewFlipperOutAnimation(this_BindLoading, also(AlphaAnimation.constructorkotlinFloat, kotlinFloat(1f, 0f), (this_) => {
                setAndroidViewAnimationAlphaAnimationDuration(this_, 250);
                setAndroidViewAnimationAlphaAnimationInterpolator(this_, LinearInterpolator.constructor());
    })) : 
    if (getAndroidWidgetViewFlipperChildCount(this_BindLoading) === 1) {
        const spinner = ProgressBar.constructorandroidcontentContext(getAndroidWidgetViewFlipperContext(this_BindLoading));
        
        color?.((color) => {
                //TODO: Make this actually show the proper color. Currently it only makes it white.
                const colorValue = getAndroidWidgetViewFlipperResources(this_BindLoading).getColor(color);
                
                setAndroidGraphicsDrawableDrawableColorFilter(getAndroidWidgetProgressBarIndeterminateDrawable(spinner), LightingColorFilter.constructorkotlinInt, kotlinInt(0xFFFFFFFF - colorValue, colorValue));
        })(this);
        addView(spinner, 1, FrameLayout.LayoutParams.constructorkotlinInt, kotlinInt, kotlinInt(WRAP_CONTENT, WRAP_CONTENT, Gravity.CENTER));
    }
    return ioReactivexDisposablesDisposableUntil(comLightningkiteKhrysalisObservablesObservablePropertySubscribeBy(loading, undefined, undefined, (it) => setAndroidWidgetViewFlipperDisplayedChild(this_BindLoading, it ? 1 : 0)), getAndroidViewViewRemoved(this_BindLoading));
}

