// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: observables/binding/ViewFlipper.binding.actual.kt
// Package: com.lightningkite.khrysalis.observables.binding
import { ObservableProperty } from './../ObservableProperty.shared'
import { ColorResource } from './../../views/ResourceTypes.actual'

//! Declares com.lightningkite.khrysalis.observables.binding.bindLoading
export function AndroidWidgetViewFlipperBindLoading(this_BindLoading: ViewFlipper, loading: ObservableProperty<Boolean>, color: (ColorResource | null) = null){}

