// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: captureWeak.shared.kt
// Package: com.lightningkite.khrysalis

//! Declares com.lightningkite.khrysalis.captureWeak
export function captureWeak<Z extends object>(capture: Z, lambda:  (a: Z) => void): () => void{
    const captured;
    
    return () => {
        const actualCaptured = captured;
        
        if (actualCaptured.equals(null)) {
            return;
        }
        this.lambda(actualCaptured!!);
    };
}

//! Declares com.lightningkite.khrysalis.captureWeak
export function captureWeak<Z extends object, A>(capture: Z, lambda:  (a: Z, b: A) => void): (a: A) => void{
    const captured;
    
    return (a) => {
        const actualCaptured = captured;
        
        if (actualCaptured.equals(null)) {
            return;
        }
        this.lambda(actualCaptured!!, a);
    };
}

//! Declares com.lightningkite.khrysalis.captureWeak
export function captureWeak<Z extends object, A, B>(capture: Z, lambda:  (a: Z, b: A, c: B) => void): (a: A, b: B) => void{
    const captured;
    
    return (a, b) => {
        const actualCaptured = captured;
        
        if (actualCaptured.equals(null)) {
            return;
        }
        this.lambda(actualCaptured!!, a, b);
    };
}

//! Declares com.lightningkite.khrysalis.captureWeak
export function captureWeak<Z extends object, A, B, C>(capture: Z, lambda:  (a: Z, b: A, c: B, d: C) => void): (a: A, b: B, c: C) => void{
    const captured;
    
    return (a, b, c) => {
        const actualCaptured = captured;
        
        if (actualCaptured.equals(null)) {
            return;
        }
        this.lambda(actualCaptured!!, a, b, c);
    };
}

//! Declares com.lightningkite.khrysalis.captureWeak
export function captureWeak<Z extends object, A, B, C, D>(
    capture: Z,
    lambda:  (a: Z, b: A, c: B, d: C, e: D) => void
): (a: A, b: B, c: C, d: D) => void{
    const captured;
    
    return (a, b, c, d) => {
        const actualCaptured = captured;
        
        if (actualCaptured.equals(null)) {
            return;
        }
        this.lambda(actualCaptured!!, a, b, c, d);
    };
}

//! Declares com.lightningkite.khrysalis.captureWeak
export function captureWeak<Z extends object, A, B, C, D, E>(
    capture: Z,
    lambda:  (a: Z, b: A, c: B, d: C, e: D, f: E) => void
): (a: A, b: B, c: C, d: D, e: E) => void{
    const captured;
    
    return (a, b, c, d, e) => {
        const actualCaptured = captured;
        
        if (actualCaptured.equals(null)) {
            return;
        }
        this.lambda(actualCaptured!!, a, b, c, d, e);
    };
}

