// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: delay.actual.kt
// Package: com.lightningkite.khrysalis
// FQImport: android.os.Looper TS Looper
// FQImport: android.os.Handler.post TS post
// FQImport: com.lightningkite.khrysalis.delay.milliseconds TS milliseconds
// FQImport: android.os.Looper.getMainLooper TS getMainLooper
// FQImport: io.reactivex.subjects.PublishSubject TS PublishSubject
// FQImport: io.reactivex.subjects.PublishSubject.create TS create
// FQImport: android.os.Handler.postDelayed TS postDelayed
// FQImport: android.os.Handler TS Handler
// FQImport: com.lightningkite.khrysalis.post.action TS action
// FQImport: com.lightningkite.khrysalis.delay.action TS action

//! Declares com.lightningkite.khrysalis.delay
export function delay(milliseconds: number, action: () => void){
    milliseconds === 0L ? this.action() : Handler.constructorandroidosLooper(Looper.getMainLooper()).postDelayed(action, milliseconds)
}

//! Declares com.lightningkite.khrysalis.post
export function post(action: () => void){
    Handler.constructorandroidosLooper(Looper.getMainLooper()).post(action);
}

//! Declares com.lightningkite.khrysalis.animationFrame
export const _animationFrame: PublishSubject<number> = PublishSubject.create();
export function getAnimationFrame(): PublishSubject<number> { return _animationFrame; }


