// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: String.extensions.actual.kt
// Package: com.lightningkite.khrysalis

//! Declares com.lightningkite.khrysalis.humanify
export function KotlinStringHumanify(this_Humanify: string): string{}

//! Declares com.lightningkite.khrysalis.toSnakeCase
export function KotlinStringToSnakeCase(this_ToSnakeCase: string): string{}

//! Declares com.lightningkite.khrysalis.formatList
export function KotlinStringFormatList(this_FormatList: string, arguments: Array<(any | null)>){}

