// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: net/HttpMediaType.actual.kt
// Package: com.lightningkite.khrysalis.net

//! Declares com.lightningkite.khrysalis.net.HttpMediaType
export type HttpMediaType = MediaType;
//! Declares com.lightningkite.khrysalis.net.HttpMediaType
export let HttpMediaType = MediaType;


//! Declares com.lightningkite.khrysalis.net.HttpMediaTypes
export class HttpMediaTypes {
    private constructor() {
        this.JSON = MediaType.parse("application/json")!!;
        this.TEXT = MediaType.parse("text/plain")!!;
        this.JPEG = MediaType.parse("image/jpeg")!!;
    }
    public static INSTANCE = new HttpMediaTypes();
    
    public readonly JSON = MediaType.parse("application/json")!!;
    
    public readonly TEXT = MediaType.parse("text/plain")!!;
    
    public readonly JPEG = MediaType.parse("image/jpeg")!!;
    
}

