// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: net/RxHttpAssist.actual.kt
// Package: com.lightningkite.khrysalis.net
import { HttpResponse } from './HttpResponse.actual'
import { Observable } from 'rxjs'

//! Declares com.lightningkite.khrysalis.net.unsuccessfulAsError
export function IoReactivexSingleUnsuccessfulAsError(this_UnsuccessfulAsError: Observable< HttpResponse>): Observable<HttpResponse>{}


//! Declares com.lightningkite.khrysalis.net.readJson
export function IoReactivexSingleReadJson<T>(this_ReadJson: Observable< HttpResponse>): Observable<T>{}

