// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: net/WebSocketFrame.shared.kt
// Package: com.lightningkite.khrysalis.net
// FQImport: com.lightningkite.khrysalis.net.WebSocketFrame.toString.<anonymous>.it TS it
// FQImport: com.lightningkite.khrysalis.net.WebSocketFrame.binary TS binary
// FQImport: com.lightningkite.khrysalis.net.WebSocketFrame.text TS text

//! Declares com.lightningkite.khrysalis.net.WebSocketFrame
export class WebSocketFrame {
    public readonly binary: (Int8Array | null);
    public readonly text: (string | null);
    public constructor(binary: (Int8Array | null) = null, text: (string | null) = null) {
        this.binary = binary;
        this.text = text;
    }
    
    public toString(): string{
        return this.text ?? ((_it)=>{
                if(_it === null) return null;
                return ((it) => `<Binary data length ${it.length}`)(_it)
        })(this.binary) ?? "<Empty Frame>";
    }
}

