name: PublishToMaven

on:
  release:
    types: published
    branches: master
  workflow_dispatch:

jobs:
  public-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        env:
          CI: true
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        with:
          arguments: :plugin:uploadArchive
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true